spring:
  application:
    name: liming-spring-cloud-netflix-eureka

server:
  port: 10001

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/